apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      imagePullSecrets:
      - name: my-registry-secret  # Reference your secret here
      containers:
      - name: netflix-clone
        image: sivanext/netflix_clone:latest
        ports:
        - containerPort: 5000
