apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-lb
  namespace: prod
spec:
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
